travis:
  secure:
    BINSTAR_TOKEN: HJ8+AS75AzibAdUcWlxGlFW0ovqaa1cQjxJIX74QqdYaYyoqBdzUJYtDTcc2Vpn61vKU0ybUyQt1eVKkhdGHd3yGpTZYHmsFHsFTu0ypw9WwaZKP5fVggpjKFX6o7+FQG5MT573ucrMNJGk8DQgMvp55utQgRJygFKt+PY6V9xOJnbOy2JG44ZnCevRE7X1OgZKVeQ8Q9L27JhmHL8lbXo/Dn106yeo9uzfgFaMnYSWZxPi2iBMCssXbYz2fVtJJgxKO/q4kCTESWbpfsrgY150Xt0uFMCN5tqooGWTStHWPKB07aRjr5lcUKzmApjgOhF2AjG8BND+SPyaBs21YcCFBeijIEDxicB85ppitydTuhfthhgHCwWS79a0voezdF9WM1E1KJ1a66J27JSiThS5A8IRastXj7eDQcfxe09dWJDnXMf3DReay3OZQmQqzYBl0fubkAvgnNL4I58w3KV6FTzC4zeXbpq76dnC6cnhZ3jL6NolxwXSJvd9+FlD7QTo/pjLMb0M0mRPmqC5/w0U8eZvac356dlWhjoafWIPQ52iFJRLl5O9XQEAZ3ZYd0YQYnK/ryqqY81wbZBL20oOi1kKXx5F/VfF/ykqOimCBMqUDUDX0yEW8KbmnAWAw7AGl2zN9Hu5yjacEsVw7ipV+dnSK7ua2dJgA7fOwDtk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
