travis:
  secure:
    BINSTAR_TOKEN: XGECtSynT4xo9VmqoXPHlwSPsnz5H3YMJlpi8JIJzyaSvnnfdRPEzw9gGqIm9pkbfqMw90GrcYYRbzXEB3uUmiiQ6D27MSQeL62h2eAQ4KZSCo3FVuhWOQj4Wbp189wZhSC8iL/FNfZKRQwvFBY6VTzgsLOhvJ2lN82HXSCtzvQP5RzQq9B7onjXzNANCbI6ETcatm4RNaoiwmVPV+RnRUlJGrXQUaAAWxWf1IOIz/pjoj0lGn9L1bsBmBX8xWeT868lyiVu4dk/wO+Oy/kTHGF7akwkfredwjhSxNvNHcPz8PRGOYxcp7RSbntY/HGonY5CKcxC235b1Dy9UwsDUQPxrES/yuIlXX/yStuDSogVgkiJz2TMqv1UioMQavvPBtvUsa4SOVSr2eeTI++zcHrS5xxvFYt15svbc6VdjSEeN/PW+XKXg/Zei5ZsB8XZsq/9Cb3r+f+8c6t3LqwDVM7CxqLKoXypsgMfzlz+GjWLy9biLUcvqOvySKIzNjsOOMt4z9e4A36fADzAK+cVkhwebaqNUwvn3F5tRszyO1Gj3J90AJfyIwIc6U27NRBCLnvgcNTrc09XEy6pga3WrBEII+ZX2wXQWtsUkTk5bliSE2o5V7NIjOnYgWGc/nG6dVhbP4HZ9HHFE2KJ+EyiTIWO0kRqRBRJFDLfFobIpho=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
